---
title: "ASSIGNMENT 7"
author: "Simek, Kathryn"
date: '2010-10-18'
output:
  pdf_document: default
  html_notebook: default
---

```{r}
## Set the working directory to the root of your DSC 520 directory
setwd("C:/Users/katie/OneDrive/Documents/GitHub/dsc520")

## Load the `data/r4ds/heights.csv` to
heights_df <- read.csv("data/r4ds/heights.csv")

# Fit a linear model
earn_lm <-  lm(earn ~ height + ed + 
                 race + sex + age, data=heights_df)

# View the summary of your model
summary(earn_lm)
```
```{r}
predicted_df <- data.frame(
  earn = predict(earn_lm, heights_df),
  ed=heights_df$ed, race=heights_df$race, height=heights_df$height,
  age= heights_df$age, sex=heights_df$sex)
```

```{r}
## Compute deviation (i.e. residuals)
mean_earn <- mean(heights_df$earn)
mean_earn
```

```{r}
## Corrected Sum of Squares Total
sst <- sum((mean_earn - heights_df$earn)^2)
sst
```

```{r}
## Corrected Sum of Squares for Model
ssm <- sum((mean_earn - predicted_df$earn)^2)
ssm
```

```{r}
## Residuals
residuals <- heights_df$earn - predicted_df$earn
head(residuals)
```

```{r}
## Sum of Squares for Error
sse <- sum(residuals^2)
sse
```

```{r}
## R Squared
r_squared <- ssm / sst
r_squared
```

```{r}
## Compute deviation (i.e. residuals)
mean_earn <- mean(heights_df$earn)
mean_earn
```

```{r}

## Corrected Sum of Squares Total
sst <- sum((mean_earn - heights_df$earn)^2)
sst
```

```{r}
## Corrected Sum of Squares for Model
ssm <- sum((mean_earn - predicted_df$earn)^2)
ssm
```

```{r}
## Number of observations
n <- 1192
## Number of regression paramaters
p <- 8
## Corrected Degrees of Freedom for Model
dfm <- (p-1)
dfm
```

```{r}
## Degrees of Freedom for Error
dfe <- (n-p)
dfe
```

```{r}
## Corrected Degrees of Freedom Total:   DFT = n - 1
dft <- (n-1)
dft
```

```{r}

## Mean of Squares for Model:   MSM = SSM / DFM
msm <- ssm / dfm
msm
```

```{r}
## Mean of Squares for Error:   MSE = SSE / DFE
mse <- sse / dfe
mse
```

```{r}
## Mean of Squares Total:   MST = SST / DFT
mst <- sst / dft
mst
```

```{r}
## F Statistic
f_score <- msm / mse
f_score
```

```{r}
## Adjusted R Squared R2 = 1 - (1 - R2)(n - 1) / (n - p)
adjusted_r_squared <- 1 - (1 - r_squared)*(dft) / (dfe)
adjusted_r_squared
```